= Introducción
:page-layout: home
:!sectids:

Golden Paths, o Software Templates, son un concepto básico y fundamental en las plataformas de desarrollo interno (Internal Developer Platform - IDP) bien diseñadas.

La idea principal de este concepto es que la plataforma ofrece un modelo previamente diseñado y respaldado para crear e implementar un software en particular. Si un equipo puede trabajar en este modelo porque los requisitos así lo permiten, es entonces cuando se benefecia de ese modelo previamente diseñado en su evolución hacia producción sin necesidad de un conocimiento de los detalles de la tecnología y componentes que utiliza.

Este enfoque acelera los casos de uso típicos del desarrollo de aplicaciones (onboarding de un nuevo miembro del equipo, onboarding de una nueva aplicación), y al mismo tiempo incorpora las buenas practicas que se han aprendido en el pasado. Cuanto más sofisticado sea este Golden Path, se adoptará más, proporcionando una mayor uniformidad de configuración y comportamiento de todas las aplicaciones que lo utilicen.

Dicho esto, ¿qué forma un Golden Path? Un Golden Path tendrá, como mínimo, los siguientes ingredientes:

* Un repositorio de código que se puede utilizar como plantilla. Puede ser un simple _Hello World_, pero con las configuraciones básicas necesarias para que un desarrollador puede comenzar rápidamente con los IDEs de la compañía e incorporar las buenas practicas para el desarrollo del código de la aplicación.

* Un pipeline que construye, empaquete, despliegue y propague los artefactos entre los entornos hasta producción. El pipeline tendrá todos los pasos necesarios por la organización confie plenamente en el código compilado y propagado entre los diferentes entornos.

* Un conjunto de manifiestos declarativos para desplegar la aplicación en los entornos. Pueden ser Helm charts, configuración de Kustomize, o cualquier otra forma de configuración descriptiva.

* Integración de mecanismos de observabilidad de la aplicación con la platforma. La Observabilidad (logs, trazas, métricas y alertas) es una capacidad fundamental que debe proporcionar la plataforma. Se debe definir exactamente qué observar en una aplicación específica como parte del manifiesto de implementación. Un Golden Path debe proporcionar valores predeterminados razonables para las configuraciones de observabilidad.
